---
title: "cest-1.2_AnteriorTouch_Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(kableExtra)
library(magrittr)
theme_set(theme_classic())
```


```{r data load, message=FALSE}
AntTouch <- read_csv('cest1.2_anterior_touch_merged.csv') %>%
  mutate(plate = as.factor(plate))

#vector to filter out dates with possible contamination
dates_contaminated <- c("7/7/2021","7/8/2021","7/14/2021","7/15/2021", "12/7/2021")

```

```{r general bodybend and tailtouch plots, fig.height=8, fig.width = 10}

#bodybend boxplot, by date
bodybendPlot <- AntTouch %>%
  filter(is.na(note), 
         time_off_food != 30, 
         is.na(additive), 
         genotype != "daf-22",
         food == "OP50",  
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = date, fill = genotype, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior touch response",
 y = "number of body bends per reversal", x = "Date") 

#tail touch bar plot, by date
tailtouchPlot <- 
  AntTouch %>%
  ungroup() %>%
  filter(is.na(note), 
         is.na(additive),  
         food == "OP50", 
         genotype != "daf-22",
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
  geom_bar(position = "fill") +
  labs(title = "Tail touch probability in cest-1.2",
       y = "proportion of tail touch events") +
  facet_grid(.~date) +
    scale_fill_brewer(palette = "Paired")

#bodybend bar plot, combined
bodybendPlot2 <- AntTouch %>%
  filter(is.na(note), 
         time_off_food != 30, 
         is.na(additive), 
         food == "OP50",
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = 1, fill = genotype, y = bends)) +
  stat_summary(aes(fill= genotype),
               geom = "bar", 
               fun = "mean", 
               width = 0.3, 
               position = position_dodge(width = .4)) +
 # ggbeeswarm::geom_quasirandom(aes(group = genotype),
                              # pch=1,
                              # width = .075,
                              # alpha = 0.6,
                              # dodge.width = .4) +
  stat_summary(geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = .4)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(
 y = "number of body bends per reversal") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

#tail touch bar plot, combined
tailtouchPlot2 <- AntTouch %>%
  ungroup() %>%
  filter(is.na(note), 
         is.na(additive),
         food == "OP50",
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
  geom_bar(position = "fill",
           width = 0.75) +
  labs(fill = "tail touch",
       y = "proportion of tail touch events") +
  scale_fill_brewer(palette = "Paired")

(bodybendPlot / tailtouchPlot) | (bodybendPlot2 / tailtouchPlot2)
```
```{r basic statistics}

#body bends comparison of means
AntTouchSimplified <- AntTouch %>% 
  filter(is.na(note), 
         time_off_food != 30, 
         is.na(additive), 
         food == "OP50",
         !date %in% dates_contaminated) %>%
  select(genotype, bends)

t.test(bends ~ genotype, data = AntTouchSimplified)

standard.error <- function(x) sd(x)/ sqrt(length(x))

standard.error(AntTouchSimplified$bends[AntTouchSimplified$genotype == "N2"])

standard.error(AntTouchSimplified$bends[AntTouchSimplified$genotype == "cest-1.2"])

```


```{r tnaA experiment, fig.height=10, fig.width = 15}

#tnaA bodybends plot by date
tnaAbodybendPlot <- AntTouch %>%
  filter(is.na(note),
         time_off_food != 30,
         !food %in% c("OP50", "JUb39", "tdcKO"),
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = genotype, fill = food, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior touch response",
 y = "number of body bends per reversal") +
  facet_grid(.~ date)


#bodybend bar plot, combined
tnaAbodybendPlot2 <- AntTouch %>%
 filter(is.na(note), 
         is.na(additive),  
         !food %in% c("OP50", "JUb39", "tdcKO"), 
         genotype != "daf-22",
         !date %in% dates_contaminated) %>%
  ggplot(aes(x = genotype, fill = food, y = bends)) +
  stat_summary(aes(fill= food),
               geom = "bar", 
               fun = "mean", 
               width = 0.5, 
               position = position_dodge(width = .65)) +
  stat_summary(geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = .65)) +
  scale_color_brewer(palette = "Set2") +
  scale_fill_brewer(palette = "Set2") +
   labs(
 y = "number of body bends per reversal")


(tnaAbodybendPlot | tnaAbodybendPlot2)


```
```{r basic stats for tnaA experiment}

AntTouch_BW <- AntTouch %>% 
  filter(is.na(note), 
         time_off_food != 30, 
         is.na(additive), 
         food == "BW25113",
         !date %in% dates_contaminated) %>%
  select(genotype, bends)

t.test(bends ~ genotype, data = AntTouch_BW)

AntTouch_tnaA <- AntTouch %>% 
  filter(is.na(note), 
         time_off_food != 30, 
         is.na(additive), 
         food == "tnaA",
         !date %in% dates_contaminated) %>%
  select(genotype, bends)

t.test(bends ~ genotype, data = AntTouch_tnaA)

```

```{r, STARS II figure, fig.height = 10, fig.width = 10}

#png("stars.png", width = 500, height = 500)

(tnaAbodybendPlot/tailtouchPlot2 | bodybendPlot2/tnaAbodybendPlot2)

png("cest-1.2_bodybend_plot.png")
(bodybendPlot2)

png("cest-1.2_tailtouch_plot.png")
(tailtouchPlot2)

png("cest-1.2_tnaAexperiment_plot.png")
(tnaAbodybendPlot2)

```

