---
title: "Starvation"
author: "Julia Balch"
date: '2022-09-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(kableExtra)
library(magrittr)
library(viridis)
theme_set(theme_classic())
```

```{r data load, message=FALSE}
df <- read_csv('Starvation_Data.csv') %>%
  
mutate(Percent_Survival = ((100* Alive)/(Dead + Alive)), 
       Percent_Bagged = ((100* Bagged)/(Dead + Alive)),
       condition = (paste(Genotype, Food)))

```
```{r plots}
(SurvivalPlot <- df %>%
  filter(Food != "BW",Food != "tnaA") %>%
  ggplot(aes(x = Time_Off_Food_Hours , color = Genotype, y = Percent_Survival)) +
  geom_line() +
 scale_color_viridis(discrete = TRUE, option = "A", alpha = 0.65) +
    scale_fill_viridis(discrete = TRUE, option = "A", alpha = 0.65))
```

```{r plot}


(BaggingPlot <- df %>%
  filter(Genotype != "tdc-1", Food != "BW") %>%
  ggplot(aes(x = Time_Off_Food_Hours , color = condition, y = Percent_Bagged)) +
  geom_point(aes(shape = Food), size = 3.5)+
  geom_line(size = 1) +
  scale_color_manual(values = c("#F2D39A","#F2D39A","#C4B399", "#F5E7C0","#bebebe", "#bebebe")) +
   labs(y = "Percent Bagged", x = "Time Off Food (hours)") +
   theme(axis.text=element_text(size=15), axis.title =element_text(size=15)))
```


